micronaut:
  application:
    name: jpaCrudApp2
  server:
    cors:
      enabled: true
      configurations:
        allowedHeaders:
          - Content-Type
        allowedMethods:
          - GET
          - POST
          - DELETE
        allowedOrigins:
          - http://127.0.0.1:3000
          - http://127.0.0.1:8080
          - http://127.0.0.1:5173

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/crudTest
    driver-class-name: org.postgresql.Driver
    username: johnny
    password: mysecretpassword
    db-type: postgres
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
