micronaut:
  application:
    name: jpaCrudApp2
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/crudTest
    driver-class-name: org.postgresql.Driver
    username: johnny
    password: mysecretpassword
    db-type: postgres
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
